baseURL = 'https://ardalis.github.io/CleanArchitecture/'
languageCode = 'en-us'
title = 'Ardalis Clean Architecture'
theme = 'hugo-book' # A popular, clean, and minimal docs theme

[params]
  BookRepo = 'https://github.com/ardalis/CleanArchitecture'
  BookEditPath = 'edit/main/docs'
